# sources.yml

version: 2

sources:
  - name: raw
    database: jackdoyle
    schema: public
    tables:
      - name: clients
      - name: projects
      - name: partners
      - name: sales
      - name: finance
      - name: logistics
